name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Initialize RDP via LiteManager
    runs-on: windows-latest

    steps:
    - name: Download & Install Essentials
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/chamod12/1m_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

    - name: Connect to LiteManager
      run: |
        cmd /c show.bat

    - name: Start Time Counter
      run: |
        cmd /c loop.bat
